const IMAGES = {
  Logo: require('../assets/icons/Logo.png'),
  Back: require('../assets/icons/BackIcon.png'),
  Man: require('../assets/images/man.png'),
  Man_Coat: require('../assets/images/man_coat.png'),
  Leads: require('../assets/images/leads.png'),
  ContactUpload: require('../assets/images/contact.png'),
  SubscriptionCard: require('../assets/images/subscription_card.png'),
  Apple: require('../assets/icons/Apple.png'),
  Google: require('../assets/icons/Google.png'),
  Support: require('../assets/icons/Support.png'),
  Home: require('../assets/icons/Home.png'),
  Mycards: require('../assets/icons/Mycards.png'),
  Insights: require('../assets/icons/Insights.png'),
  Contact: require('../assets/icons/Contact.png'),
  Theme: require('../assets/images/theme1.png'),
  Theme1: require('../assets/images/Theme2.png'),
  Theme2: require('../assets/images/Theme3.png'),
  Profile:require('../assets/icons/profileoutline.png'),
  Instagram:require('../assets/icons/socialmedia/INS.png'),
  Facebook:require('../assets/icons/socialmedia/Fb.png'),
  Tiktok:require('../assets/icons/socialmedia/TT.png'),
  Linkedin:require('../assets/icons/socialmedia/IN.png'),
  Whatsapp:require('../assets/icons/socialmedia/WU.png'),
  Youtube:require('../assets/icons/socialmedia/YT.png'),
  Snapchat:require('../assets/icons/socialmedia/SC.png'),
  Threads:require('../assets/icons/socialmedia/TH.png'),
  TWI:require('../assets/icons/socialmedia/TWI.png'),
  Telegram:require('../assets/icons/socialmedia/TELE.png'),
  Ch:require('../assets/icons/socialmedia/CH.png'),
  Twitter:require('../assets/icons/socialmedia/TW.png'),
  PROFILE:require('../assets/images/PROFILE.png'),
  BeardMan:require('../assets/images/BeardMan.png'),
  BlackFB:require('../assets/icons/BlackFB.png'),
  BlackIns:require('../assets/icons/BlackIns.png'),
  BlackLN:require('../assets/icons/BlackLN.png'),
  BlackTk:require('../assets/icons/BlackTK.png'),
  BlackX:require('../assets/icons/BlackX.png'),
  BlackYT:require('../assets/icons/BlackYT.png'),
  Channel:require('../assets/images/channelcover.png'),
  Lines:require('../assets/images/Lines.png'),
  BlackDesk:require("../assets/images/Desk.png"),
  Saveicon:require("../assets/icons/Saveicon.png"),
  Mail:require("../assets/icons/Mail.png"),
  Website:require("../assets/icons/website.png"),
  Location:require("../assets/icons/Location.png"),
  Theme6:require('../assets/images/Theme6.png'),
  WhatsappIcon:require("../assets/icons/Whatsapp.png"),
  

  

  
};
export default IMAGES;
